name: explorer_app
services:
  data_explorer:
    command:
    - --base_path
    - /fondant-artifacts
    image: fndnt/data_explorer:0.10.1
    ports:
    - 8501:8501
    volumes:
    - source: /Users/cas/political_agents/microservice/app/scrapers/ParlementaireVragen/fondant-artifacts
      target: /fondant-artifacts
      type: bind
version: '3.8'
