swagger: '2.0'
info:
  title: microservice
  description: microservice
  version: 1.0.0
tags:
- name: Example
  description: Description of the example tag
consumes:
- application/json
produces:
- application/json
paths:
  /example/{path_param}:
    get:
      tags:
      - Example
      summary: Example endpoint to get information.
      operationId: app.flask.routes.Example.get
      parameters:
      - name: query_arg
        description: Query argument
        in: query
        required: true
        type: string
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/response-1'
    post:
      operationId: app.flask.routes.Example.post
      tags:
      - Example
      summary: Example endpoint to post information.
      parameters:
      - description: Example payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/payload'
      produces:
      - application/json
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/response-2'
    parameters:
    - name: path_param
      description: Path parameter
      in: path
      required: true
      type: string
definitions:
  payload:
    type: object
    properties:
      id:
        description: Test ID
        type: string
      data:
        description: Test data
        type: object
    required:
    - id
    - data
  response-1:
    type: object
    properties:
      path:
        description: Path property
        type: string
      query:
        description: Query property
        type: string
    required:
    - path
    - query
  response-2:
    type: object
    properties:
      path:
        description: Path property
        type: string
      payload:
        description: Body property
        type: string
    required:
    - path
    - payload
