name: pv_scraper
services:
  extract_pdf_text_component:
    build:
      args: []
      context: /Users/cas/Documents/political_agents/src/pipelines/components/scraper_components/extract_pdf_text_component
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "pv_scraper", "run_id":
      "pv_scraper-20240327151240", "component_id": "extract_pdf_text_component", "cache_key":
      "5aac49ac2e86d423bd45a1d20307c36c"}'
    - --output_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/extract_pdf_text_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "extract_pdf_text_component", "image": "extract_pdf_text_component:latest",
      "description": "Custom reusable component to download the text from pdf download
      links", "consumes": {"Download link href": {"type": "string"}}, "produces":
      {"text": {"type": "string"}}}, "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/fetchlink_pv_component/manifest.json
    depends_on:
      fetchlink_pv_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
    - /Users/cas/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
  fetchlink_pv_component:
    build:
      args: []
      context: /Users/cas/Documents/political_agents/src/pipelines/components/scraper_components/fetchlinks_pv_component
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "pv_scraper", "run_id":
      "pv_scraper-20240327151240", "component_id": "fetchlink_pv_component", "cache_key":
      "f6196e2aad818b294137865fcfb108f1"}'
    - --output_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/fetchlink_pv_component/manifest.json
    - --link
    - https://www.vlaamsparlement.be/ajax/document-overview?page=0&period=current_year_of_office&current_year_of_office_value=2022-2023&aggregaat%5B%5D=Vraag%20of%20interpellatie&aggregaattype%5B%5D=Schriftelijke%20vraag
    - --num_pages
    - '1'
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "fetchlink_pv_component", "image": "fetchlink_pv_component:latest",
      "description": "Custom component to fetch all the links directing to the parliamentairy
      questions from the website of the flemish government", "produces": {"File Name":
      {"type": "string"}, "Card title": {"type": "string"}, "Document number": {"type":
      "string"}, "View link text": {"type": "string"}, "View link href": {"type":
      "string"}, "Download link text": {"type": "string"}, "Download link href": {"type":
      "string"}}, "args": {"link": {"description": "The baseline link to the website
      of the flemish government", "type": "str", "default": "https://www.vlaamsparlement.be/ajax/document-overview?page=0&period=current_year_of_office&current_year_of_office_value=2022-2023&aggregaat%5B%5D=Vraag%20of%20interpellatie&aggregaattype%5B%5D=Schriftelijke%20vraag&thema%5B%5D=Natuur%20en%20Milieu"},
      "num_pages": {"description": "The number of pages to scrape", "type": "int",
      "default": 1}}}, "consumes": {}, "produces": {}}'
    depends_on: {}
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
    - /Users/cas/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
  regex_pv_component:
    build:
      args: []
      context: /Users/cas/Documents/political_agents/src/pipelines/components/scraper_components/regex_pv_component
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "pv_scraper", "run_id":
      "pv_scraper-20240327151240", "component_id": "regex_pv_component", "cache_key":
      "bfe2dad42895f22bdc30f56823351ef1"}'
    - --output_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/regex_pv_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "regex_pv_component", "image": "regex_pv_component:latest",
      "description": "This container is responsible for extracting key information
      from the text of a Parliamentary Question.", "consumes": {"text": {"type": "string"}},
      "produces": {"sender": {"type": "string"}, "responder": {"type": "string"},
      "questions": {"type": "string"}, "answers": {"type": "string"}, "jurisdiction":
      {"type": "string"}, "topic": {"type": "string"}, "date": {"type": "string"},
      "number": {"type": "string"}}}, "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/extract_pdf_text_component/manifest.json
    depends_on:
      extract_pdf_text_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
    - /Users/cas/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
  write_to_file:
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "pv_scraper", "run_id":
      "pv_scraper-20240327151240", "component_id": "write_to_file", "cache_key": "4bcf99418c95c9c617dc997f743b0ffa"}'
    - --output_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/write_to_file/manifest.json
    - --path
    - gs://cedar-talent-417009_scrape/pv
    - --format
    - parquet
    - --cache
    - 'True'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "Write to file", "image": "fndnt/write_to_file:0.10.1",
      "description": "A Fondant component to write a dataset to file on a local machine
      or to a cloud storage bucket. The dataset can be written as csv or parquet.",
      "tags": ["Data writing"], "consumes": {"additionalProperties": true}, "args":
      {"path": {"description": "Path to store the dataset, whether it''s a local path
      or a cloud storage bucket,  must be specified. A separate filename will be generated
      for each partition. If you are using the local runner and export the data to
      a local directory,  ensure that you mount the path to the directory using the
      `--extra-volumes` argument.", "type": "str"}, "format": {"description": "Format
      for storing the dataframe can be either `csv` or `parquet`. As default  `parquet`
      is used. The CSV files contain the column as a header and use a comma as a delimiter.",
      "type": "str", "default": "parquet"}}}, "consumes": {}, "produces": {}}'
    - --input_manifest_path
    - /fondant-artifacts/pv_scraper/pv_scraper-20240327151240/regex_pv_component/manifest.json
    depends_on:
      regex_pv_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    image: fndnt/write_to_file:0.10.1
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
    - /Users/cas/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json
version: '3.8'
