name: pd_scraper
services:
  chunk_text:
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "pd_scraper", "run_id":
      "pd_scraper-20240405094437", "component_id": "chunk_text", "cache_key": "01fc5b2e720762aeb45b419aca33bbc1"}'
    - --output_manifest_path
    - /fondant-artifacts/pd_scraper/pd_scraper-20240405094437/chunk_text/manifest.json
    - --chunk_strategy
    - RecursiveCharacterTextSplitter
    - --chunk_kwargs
    - '{"chunk_size": 512, "chunk_overlap": 40}'
    - --cache
    - 'True'
    - --operation_spec
    - '{"specification": {"name": "Chunk text", "image": "fndnt/chunk_text:0.11.2",
      "description": "Component that chunks text into smaller segments \n\nThis component
      takes a body of text and chunks into small chunks. The id of the returned dataset\nconsists
      of the id of the original document followed by the chunk index.\n\nDifferent
      chunking strategies can be used. The default is to use the \"recursive\" strategy
      which\n  recursively splits the text into smaller chunks until the chunk size
      is reached. \n\nMore information about the different chunking strategies can
      be here:\n- https://python.langchain.com/docs/modules/data_connection/document_transformers/\n-
      https://www.pinecone.io/learn/chunking-strategies/\n", "tags": ["Text processing"],
      "consumes": {"text": {"type": "string"}}, "produces": {"text": {"type": "string"},
      "original_document_id": {"type": "string"}}, "previous_index": "original_document_id",
      "args": {"chunk_strategy": {"description": "The strategy to use for chunking
      the text. One of [''RecursiveCharacterTextSplitter'', ''HTMLHeaderTextSplitter'',
      ''CharacterTextSplitter'', ''Language'', ''MarkdownHeaderTextSplitter'', ''MarkdownTextSplitter'',
      ''SentenceTransformersTokenTextSplitter'', ''LatexTextSplitter'', ''SpacyTextSplitter'',
      ''TokenTextSplitter'', ''NLTKTextSplitter'', ''PythonCodeTextSplitter'', ''character'',
      ''NLTK'', ''SpaCy'']", "type": "str", "default": "RecursiveCharacterTextSplitter"},
      "chunk_kwargs": {"description": "The arguments to pass to the chunking strategy",
      "type": "dict", "default": {}}, "language_text_splitter": {"description": "The
      programming language to use for splitting text into sentences if \"language\"
      is selected as the splitter. Check  https://python.langchain.com/docs/modules/data_connection/document_transformers/code_splitter
      for more information on supported languages.", "type": "str", "default": "None"}}},
      "consumes": {"text": {"type": "string"}}, "produces": {}}'
    - --input_manifest_path
    - /fondant-artifacts/pd_scraper/pd_scraper-20240405094437/pd_speech_extractor_component/manifest.json
    depends_on:
      pd_speech_extractor_component:
        condition: service_completed_successfully
    entrypoint:
    - fondant
    - execute
    - main
    image: fndnt/chunk_text:0.11.2
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
  pd_speech_extractor_component:
    build:
      args: []
      context: /Users/cas/Documents/political_agents/src/pipelines/components/scraper_components/pd_speech_extractor_component
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "pd_scraper", "run_id":
      "pd_scraper-20240405094437", "component_id": "pd_speech_extractor_component",
      "cache_key": "41572ff6b8592d51696a6e4eaccd9a61"}'
    - --output_manifest_path
    - /fondant-artifacts/pd_scraper/pd_scraper-20240405094437/pd_speech_extractor_component/manifest.json
    - --num_pages
    - '1'
    - --cache
    - 'True'
    - --operation_spec
    - '{"specification": {"name": "pd_speech_extractor_component", "image": "pd_speech_extractor_component:1.0.0",
      "description": "Custom component to extract all the speeches from the debates
      on the website of the flemish government", "produces": {"card_title": {"type":
      "string"}, "download_href": {"type": "string"}, "profile_href": {"type": "string"},
      "faction": {"type": "string"}, "name": {"type": "string"}, "text": {"type":
      "string"}}, "args": {"num_pages": {"description": "The number of pages to scrape",
      "type": "int", "default": 1}}}, "consumes": {}, "produces": {}}'
    depends_on: {}
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
version: '3.8'
