name: bvr_scraper
services:
  load_bvr_component:
    build:
      args: []
      context: /Users/jensbontinck/projects/personal-work/political_copilot/src/pipelines/components/scraper_components/load_bvr_component
    command:
    - --metadata
    - '{"base_path": "/fondant-artifacts", "pipeline_name": "bvr_scraper", "run_id":
      "bvr_scraper-20240312115126", "component_id": "load_bvr_component", "cache_key":
      "cb08c6ba1214d9ec3725f49af1e5c213"}'
    - --output_manifest_path
    - /fondant-artifacts/bvr_scraper/bvr_scraper-20240312115126/load_bvr_component/manifest.json
    - --cache
    - 'False'
    - --cluster_type
    - default
    - --operation_spec
    - '{"specification": {"name": "load_bvr_component", "image": "load_bvr_component:latest",
      "description": "Custom component to load the decisions of the flemish government"},
      "consumes": {}, "produces": {}}'
    depends_on: {}
    entrypoint:
    - fondant
    - execute
    - main
    labels:
      pipeline_description: null
    ports:
    - 8787:8787
    volumes:
    - source: /Users/jensbontinck/projects/personal-work/political_copilot/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
version: '3.8'
