name: explorer_app
services:
  data_explorer:
    command:
    - --base_path
    - /fondant-artifacts
    image: fndnt/data_explorer:0.11.2
    ports:
    - 8501:8501
    volumes:
    - source: /Users/cas/Documents/political_agents/src/pipelines/fondant-artifacts
      target: /fondant-artifacts
      type: bind
version: '3.8'
